services:
  app:
    build:
      context: ./app
      target: dev   # Nutzt das 'dev'-Target aus deinem Dockerfile
    volumes:
      - ./app/src:/app/src   # Hot-reload: Source Code wird gemountet
      - ./app/migrations:/app/migrations 
    ports:
      - "8000:8000"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres #must be changed on prod 

  web:
    build:
      context: ./web
      target: dev
    depends_on:
      - app
    volumes:
      - ./web:/web
    ports:
      - "80:80"
      - "5173:5173"

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
