server {
    server_name localhost;
    autoindex off;
    server_tokens off;

    tcp_nopush on;
    tcp_nodelay on;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Serve your service worker and manifest files
    location ~* \.(?:manifest\.json|service-worker\.js)$ {
        expires 0;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        access_log off;
    }

    # Serve static files with cache headers
    location ~* \.(?:js|css|ico|png|jpg|jpeg|svg|gif|eot|otf|ttf|woff|woff2)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
    }
}
